# Generated by Django 3.0.6 on 2020-06-16 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='linked_gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gig.Gig'),
        ),
    ]
